version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: stratego-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stratego-db
      MYSQL_USER: stratego
      MYSQL_PASSWORD: stratego
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
